version: '3.6'

services:
  node:
    container_name: api_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8084:8084'
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    networks:
     - codernet

  db:
    container_name: db_1
    restart: always
    image: bitnami/mongodb:4.2
    ports:
      - '27018:27017'
    environment:
      - MONGODB_ROOT_PASSWORD=123456
      - MONGODB_USERNAME=coder
      - MONGODB_PASSWORD=coder
      - MONGODB_DATABASE=coder
    networks:
      - codernet

  mail:
    container_name: mail_1
    restart: always
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
    networks:
     - codernet

networks:
  codernet:
    driver: 'bridge'
   